name: Python lint, format and test

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/python.yml"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/python.yml"

defaults:
  run:
    working-directory: api

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          make install
          make install-dev

      - name: Lint
        run: make lint

      - name: Format
        run: make ARGS=--check fmt

      - name: Test
        run: make test
